env_file:
  - .env
version: "${VERSION}"
services:
  php-fpm:
    build:
      context: ${ROOT_PATH}/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ${PHP_WWW_DIR}:/data/www:rw
      - ${PHP_CONF_INI_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${PHP_LOG_DIR}:/var/log/php-fpm:rw
    networks:
      - back-network
      - font-network
    depends_on:
      - mysql
      - redis
    restart: always
    command: php-fpm

  nginx:
    build:
      context: ${ROOT_PATH}/nginx
      dockerfile: Dockerfile
    depends_on:
      - php-fpm
    volumes:
      - ${NGINX_WWW_DIR}:/data/www:rw
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d:ro
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    networks:
      - font-network
    restart: always
    command: nginx -g 'daemon off;'

  mysql:
    build:
      context: ${ROOT_PATH}/mysql
      dockerfile: Dockerfile
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back-network
    restart: always
    command: "--character-set-server=utf8mb4"

  redis:
    build:
      context: ${ROOT_PATH}/redis
      dockerfile: Dockerfile
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
      - ${REDIS_LOG_DIR}:/var/log/redis
    networks:
      - back-network
    restart: always
networks:
  font-network:
    driver: bridge
  back-network:
    driver: bridge