version: "3.0"

services:
  php-fpm:
    build:
      context: ${SERVICE_PATH}/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        TIME_ZONE: ${TIME_ZONE}
    ports:
      - "9000:9000"
    volumes:
      - ${WWW_PATH}:/data/www:rw
      - ${SERVICE_PATH}${PHP_CONF_INI_FILE}:/usr/local/etc/php/php.ini:ro
      - ${SERVICE_PATH}${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${SERVICE_PATH}${PHP_LOG_DIR}:/var/log/php-fpm:rw
    networks:
      - back-network
      - font-network
    depends_on:
      - mysql
      - redis
    restart: always
    command: php-fpm

  nginx:
    build:
      context: ${SERVICE_PATH}/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TIME_ZONE: ${TIME_ZONE}
    depends_on:
      - php-fpm
    volumes:
      - ${WWW_PATH}:/data/www:rw
      - ${SERVICE_PATH}${NGINX_CONF_DIR}:/etc/nginx/conf.d:ro
      - ${SERVICE_PATH}${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${SERVICE_PATH}${NGINX_LOG_DIR}:/var/log/nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    networks:
      - font-network
    restart: always
    command: nginx -g 'daemon off;'

  mysql:
    build:
      context: ${SERVICE_PATH}/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        TIME_ZONE: ${TIME_ZONE}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${SERVICE_PATH}${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      - ${SERVICE_PATH}${MYSQL_LOG_DIR}:/var/log/mysql:rw
      - ${SERVICE_PATH}${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back-network
    restart: always
    command: "--character-set-server=utf8mb4"

  redis:
    build:
      context: ${SERVICE_PATH}/redis
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: ${REDIS_VERSION}
        TIME_ZONE: ${TIME_ZONE}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${SERVICE_PATH}${REDIS_DATA_DIR}:/data
      - ${SERVICE_PATH}${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
      - ${SERVICE_PATH}${REDIS_LOG_DIR}:/var/log/redis
    networks:
      - back-network
    restart: always
networks:
  font-network:
    driver: bridge
  back-network:
    driver: bridge